version: '3.8'

services:
  web:
    build: .
    image: chat-app:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
